### PR TITLE
https://github.com/dleovl/Bootstrap

### PR DESCRIPTION
**Pull request by imnltsa**
@Stillrem There is no need for an automatically building cron as this has already been available from the start at [https://github.com/dleovl/Bootstrap](https://github.com/dleovl/Bootstrap), and your posts on [r/jailbreak](https://reddit.com/r/jailbreak) and [other subreddits](https://www.reddit.com/user/allexars/) linking to this repository for even the smallest commits are nothing but clutter. I'd be fine if you were to provide any kind of improvement to the yml in any way (adding text to the release from my README PR [https://github.com/dleovl/Bootstrap/tree/readme](https://github.com/dleovl/Bootstrap/tree/readme) is NOT your own improvement, it shouldn't even be there yet actually) but you've done nothing but take work and show it off as your own for fake internet points. Get a life man.

### CODE REVIEW

**Comment by Stillrem** [comment]
Hello, but what do you mean yours, it is also built from commands like yours, only I added caching to speed up the build. In fact, there is nothing of yours in your yml.

**Comment by imnltsa** [comment]
> I added caching

Cool caching, but the rest is literally a rip-off. You don't need entirely fast builds because the cron runs after a long time anyway, and is STILL one hour between each release pushed / action completed.

I appreciate the effort to try to make it your own, but it's still a blatant rip-off.

1. A majority of the yml code is mine, and
2. You are LITERALLY using the disclaimer text that I wrote that isn't even in upstream yet

**Comment by dleovl** [comment]
> > I added caching
> 
> Cool caching, but the rest is literally a rip-off.

+ you don't need entirely fast builds because the cron runs after a long time anyway, and is STILL one hour between each release pushed / action completed

**Comment by dleovl** [comment]
I appreciate the effort to try to make it your own, but it's still a blatant rip-off.
1. A majority of the yml code is mine, and
2. You are LITERALLY using the disclaimer text that I wrote that isn't even in upstream yet

**Comment by imnltsa** [comment]
Closing for cleanliness on my repository. https://github.com/dleovl/Bootstrap

**Pull request closed without merging**
